dist: xenial

os:
  - linux

arch:
  - arm64 

addons:
  apt:
    update: true

script:
  # Install compiler, required and optional package
  - sudo apt-get install build-essential -y
  - sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev -y
  - sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev -y
  # Configure
  - mkdir build
  - cd build/
  - cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
  # Build
  - make -j7
